# Generated by Django 6.0.5 on 2026-05-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_language_theme_remove_guideprofile_user_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guides.guide'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('traveler', 'guide')},
        ),
    ]
