# Generated by Django 6.0.5 on 2026-05-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_guide'),
        ('guides', '0002_language_theme_remove_guideprofile_user_and_more'),
        ('reviews', '0002_alter_review_guide_alter_review_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuideProfile',
        ),
    ]
