# Generated by Django 6.0.5 on 2026-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0004_guide_latitude_guide_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guide",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
