# Generated by Django 6.0.5 on 2026-06-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0005_alter_guide_latitude_alter_guide_longitude"),
        ("guides", "0005_guide_favorites"),
    ]

    operations = []
