# Generated by Django 6.0.5 on 2026-06-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0006_merge_20260602_0819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
