# Generated by Django 6.0.5 on 2026-06-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0007_alter_guide_latitude_alter_guide_longitude"),
        ("guides", "0008_availability_max_people"),
    ]

    operations = []
