# Generated by Django 6.0.5 on 2026-05-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='Booking_date',
        ),
    ]
