# Generated by Django 6.0.5 on 2026-05-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_date_booking_booking_date'),
        ('guides', '0002_language_theme_remove_guideprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='guides.guide'),
        ),
    ]
