# Generated by Django 6.0.5 on 2026-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
