# Generated by Django 6.0.5 on 2026-06-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_available",
        ),
    ]
